baseURL = 'https://lssmer.github.io/'
languageCode = 'en-us'
title = 'nishimura'
theme = "smol"

# Parameters
[params]
    subtitle = ""
    dateFmt = "02.01.2006 15:04"

# Header
[menu]
  [[menu.main]]
        identifier = "posts"
        name = "Posts"
        url = "/posts/"
        weight = 1
  [[menu.main]]
	indentifier = "library"
	name = "Library"
	url = "/library"
	weight = 2

  [[menu.main]]
	indentifier = "gallery"
	name = "Gallery"
	url = "/gallery"
	weight = 3

  # Footer
  [[menu.footer]]
        name = "Github"
        url = "https://github.com/lssmer"
        weight = 1